// Generated by CoffeeScript 1.6.3
(function() {
  Array.prototype.toID = function() {
    var item, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      item = this[_i];
      _results.push(item.id);
    }
    return _results;
  };

  Array.prototype.toRecords = function(ids) {
    var id, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = ids.length; _i < _len; _i++) {
      id = ids[_i];
      _results.push(this.find(id));
    }
    return _results;
  };

}).call(this);
