// Generated by CoffeeScript 1.6.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Array.prototype.toID = function() {
    var item, res, _i, _len;
    res = [];
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      item = this[_i];
      if (typeof item.id === 'string') {
        res.push(item.id);
      }
    }
    return res;
  };

  Array.prototype.last = function() {
    var lastIndex;
    lastIndex = this.length - 1;
    return this[lastIndex];
  };

  Array.prototype.first = function() {
    return this[0];
  };

  Array.prototype.update = function(value) {
    if (Object.prototype.toString.call(value) !== '[object Array]') {
      throw new Error('passed value requires an array');
    }
    [].splice.apply(this, [0, this.length - 0].concat(value)), value;
    return this;
  };

  Array.prototype.addRemoveSelection = function(id) {
    this.toggleSelected(id);
    return this;
  };

  Array.prototype.toggleSelected = function(id) {
    var index;
    if (__indexOf.call(this, id) < 0) {
      this.unshift(id);
    } else {
      index = this.indexOf(id);
      if (index !== -1) {
        this.splice(index, 1);
      }
    }
    return this;
  };

}).call(this);
